### PR TITLE
Center camera on selected objects in preview

### PR DESCRIPTION
**Pull request by mrkubax10**
For now this only works correctly with `ChildShape`s since their size is known. With `RigidBody` it will require some more work.

### CODE REVIEW

**Comment by jordan4ibanez** [comment]
One core dev approval :+1:

**Comment by jordan4ibanez** [comment]
This is the best code I've ever seen

**Comment by kotek900** [comment]
> This is the best code I've ever seen

sounds good

**Comment by rollerozxa** [comment]
oh no why is there a binary file embedded in the PR

**Pull request merged**
